# Copyright 2012 and 2013 Lyman Gillispie
# This code is distributed under the MIT License
# Author: Lyman Gillispie

def dict_to_dat(config):
    '''Super ugly conversion method,
    Args: config - a dictionary containing all of the appropriate elements
    Returns: outstring, a valid input.dat for the Hock melt model
    '''

    outstring = []

    outstring.append('\n')
    outstring.append('\n')
    outstring.append('{daysscreenoutput}\n'.format(**config))
    outstring.append('{inpath}\n'.format(**config))
    outstring.append('{outpath}\n'.format(**config))
    outstring.append('{jdbeg}  {yearbeg}\n'.format(**config))
    outstring.append('{jdend}  {yearend}\n'.format(**config))
    outstring.append('{disyes}\n'.format(**config))
    outstring.append('{calcgridyes}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{maxmeltstakes}\n'.format(**config))
    outstring.append('{plusminus}\n'.format(**config))
    outstring.append('{do_out}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{shayes} {exkyes} {solyes} {diryes} {dir2yes} {difyes} {gloyes} {albyes} {swbyes} {linyes} {loutyes}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{netyes} {senyes} {latyes} {raiyes} {enbyes} {melyes} {ablyes} {surftempyes} {posyes} {ddfyes}\n'.format(**config))
    outstring.append('{surfyes}\n'.format(**config))
    outstring.append('{snowyes}\n'.format(**config))
    outstring.append('{daysnow}\n'.format(**config))
    outstring.append('{numbersnowdaysout}\n'.format(**config))

    outstring.append(" ".join(map(str, config['jdsurface'])) + "\n\n")

    outstring.append('{winterbalyes}\n'.format(**config))
    outstring.append('{winterjdbeg}  {winterjdend}\n'.format(**config))
    outstring.append('{summerbalyes}\n'.format(**config))
    outstring.append('{summerjdbeg}  {summerjdend}\n'.format(**config))
    outstring.append('{datesfromfileyes}\n'.format(**config))
    outstring.append('{namedatesmassbal}\n'.format(**config))
    outstring.append('{beltwidth}\n'.format(**config))
    outstring.append('{snow2zeroeachyearyes}\n'.format(**config))
    outstring.append('{snowfreeyes}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{cumulmeltyes}\n'.format(**config))
    outstring.append('{cm_or_m}\n'.format(**config))
    outstring.append('{do_out_area}\n'.format(**config))
    outstring.append('{outgridnumber}\n'.format(**config))
    outstring.append('\n')
    outstring.append('\n')

    for grid in config['outgrids']:
        outstring.append((grid['name'] + " " +
            " ".join(map(str, grid['location'])) +
            " " + str(grid['outglobnet']) + "\n"))

    outstring.append("\n")

    outstring.append('{methodinisnow}\n'.format(**config))
    outstring.append('{methodsnowalbedo}\n'.format(**config))
    outstring.append('{methodglobal}\n'.format(**config))
    outstring.append('{methodlonginstation}\n'.format(**config))
    outstring.append('{methodlongin}\n'.format(**config))
    outstring.append('{methodsurftempglac}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{methodturbul}\n'.format(**config))
    outstring.append('{method_z0Te}\n'.format(**config))
    outstring.append('{methodiceheat}\n'.format(**config))
    outstring.append('{methodnegbal}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{scalingyes}\n'.format(**config))
    outstring.append('{gamma}\n'.format(**config))
    outstring.append('{c_coefficient}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{namedgm}\n'.format(**config))
    outstring.append('{namedgmdrain}\n'.format(**config))
    outstring.append('{namedgmglac}\n'.format(**config))
    outstring.append('{namedgmslope}\n'.format(**config))
    outstring.append('{namedgmaspect}\n'.format(**config))
    outstring.append('{namedgmskyview}\n'.format(**config))
    outstring.append('{namedgmfirn}\n'.format(**config))
    outstring.append('{nameinitialsnow}\n'.format(**config))
    outstring.append('{nameklima}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{laenge}\n'.format(**config))
    outstring.append('{breite}\n'.format(**config))
    outstring.append('{reflongitude}\n'.format(**config))
    outstring.append('{rowclim}\n'.format(**config))
    outstring.append('{colclim}\n'.format(**config))
    outstring.append('{climoutsideyes}  {heightclim}\n'.format(**config))
    outstring.append('{gridsize}\n'.format(**config))
    outstring.append('{timestep}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{formatclimdata}\n'.format(**config))
    outstring.append('{maxcol}\n'.format(**config))
    outstring.append('{coltemp}\n'.format(**config))
    outstring.append('{colhum}\n'.format(**config))
    outstring.append('{colwind}\n'.format(**config))
    outstring.append('{colglob}\n'.format(**config))
    outstring.append('{colref}\n'.format(**config))
    outstring.append('{colnet}\n'.format(**config))
    outstring.append('{collongin}\n'.format(**config))
    outstring.append('{collongout}\n'.format(**config))
    outstring.append('{colprec}\n'.format(**config))
    outstring.append('{colcloud}\n'.format(**config))
    outstring.append('{coltempgradvarying}\n'.format(**config))
    outstring.append('{coldis}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{ERAtempshift}\n'.format(**config))
    outstring.append('{ERAwindshift}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{methodtempinterpol}\n'.format(**config))
    outstring.append('{tempgrad}\n'.format(**config))
    outstring.append('{tempscenario}\n'.format(**config))
    outstring.append('{precscenario}\n'.format(**config))
    outstring.append('\n')


    outstring.append((str(config["monthtempgradyes"]) + " " +
      " ".join(map(str, config["monthtempgrad"])) + "\n"))

    outstring.append((str(config["monthtempscenyes"]) + " " +
      " ".join(map(str, config["monthtempscen"])) + "\n"))

    outstring.append((str(config["monthprecipscenyes"]) + " " +
      " ".join(map(str, config["monthprecipscen"])) + "\n"))

    outstring.append("\n")

    outstring.append('{n_albfiles}\n'.format(**config))
    outstring.append('{albsnow}\n'.format(**config))
    outstring.append('{albslush}\n'.format(**config))
    outstring.append('{albice}\n'.format(**config))
    outstring.append('{albfirn}\n'.format(**config))
    outstring.append('{albrock}\n'.format(**config))
    outstring.append('{albmin}\n'.format(**config))
    outstring.append('{snowalbincrease}\n'.format(**config))
    outstring.append('{albiceproz}\n'.format(**config))
    outstring.append('{ndstart}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{split}\n'.format(**config))
    outstring.append('{prozdiffuse}\n'.format(**config))
    outstring.append('{trans}\n'.format(**config))
    outstring.append('{ratio}\n'.format(**config))
    outstring.append('{ratiodir2dir}\n'.format(**config))
    outstring.append('{surftemplapserate}\n'.format(**config))
    outstring.append('{directfromfile}\n'.format(**config))
    outstring.append('{pathdirectfile}\n'.format(**config))
    outstring.append('{daysdirect}\n'.format(**config))
    outstring.append('{slopestation}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{iterstep}\n'.format(**config))
    outstring.append('{z0wice}\n'.format(**config))
    outstring.append('{dividerz0T}\n'.format(**config))
    outstring.append('{dividerz0snow}\n'.format(**config))
    outstring.append('{z0proz}\n'.format(**config))
    outstring.append('{icez0min:.10f}\n'.format(**config))
    outstring.append('{icez0max}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{methodprecipinterpol}\n'.format(**config))
    outstring.append('{precgrad}\n'.format(**config))
    outstring.append('{precgradhigh} {precgradelev}\n'.format(**config))
    outstring.append('{preccorr}\n'.format(**config))
    outstring.append('{snowmultiplierglacier}\n'.format(**config))
    outstring.append('{snowmultiplierrock}\n'.format(**config))
    outstring.append('{threshtemp}\n'.format(**config))
    outstring.append('{onlyglacieryes}\n'.format(**config))
    outstring.append('{glacierpart}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{nameqcalc}\n'.format(**config))
    outstring.append('{nodis}\n'.format(**config))
    outstring.append('{firnkons}\n'.format(**config))
    outstring.append('{snowkons}\n'.format(**config))
    outstring.append('{icekons}\n'.format(**config))
    outstring.append('{rockkons}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{qfirnstart}\n'.format(**config))
    outstring.append('{qsnowstart}\n'.format(**config))
    outstring.append('{qicestart}\n'.format(**config))
    outstring.append('{qrockstart}\n'.format(**config))
    outstring.append('{qground}\n'.format(**config))
    outstring.append('{jdstartr2diff}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{disyesopt}\n'.format(**config))
    outstring.append('{optkA}\n'.format(**config))
    outstring.append('{startopt1}\n'.format(**config))
    outstring.append('{stepopt1}\n'.format(**config))
    outstring.append('{anzahlopt1}\n'.format(**config))
    outstring.append('{optkB}\n'.format(**config))
    outstring.append('{startopt2}\n'.format(**config))
    outstring.append('{stepopt2}\n'.format(**config))
    outstring.append('{anzahlopt2}\n'.format(**config))
    outstring.append('{namematrix}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{percolationyes}\n'.format(**config))
    outstring.append('{slushformationyes}\n'.format(**config))
    outstring.append('{densificationyes}\n'.format(**config))
    outstring.append('{wetstartyes}\n'.format(**config))
    outstring.append('{ndepths}\n'.format(**config))
    outstring.append('{factinter}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{thicknessfirst}\n'.format(**config))
    outstring.append('{thicknessdeep}\n'.format(**config))
    outstring.append('{depthdeep}\n'.format(**config))
    outstring.append('{denssnow}\n'.format(**config))
    outstring.append('{irrwatercontyes}\n'.format(**config))
    outstring.append('{irrwatercont}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{factsubsurfout}\n'.format(**config))
    outstring.append('{offsetsubsurfout}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{runoffyes} {superyes} {wateryes} {surfwateryes} {slushyes} {coldsnowyes} {coldtotyes}\n'.format(**config))
    outstring.append('\n')
    outstring.append('\n')
    outstring.append('\n')
    outstring.append('{ddmethod}\n'.format(**config))
    outstring.append('{DDFice}\n'.format(**config))
    outstring.append('{DDFsnow}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{meltfactor}\n'.format(**config))
    outstring.append('{radfactorice}\n'.format(**config))
    outstring.append('{radfactorsnow}\n'.format(**config))
    outstring.append('{debrisfactor}\n'.format(**config))
    outstring.append('\n')
    outstring.append('{coordinatesyes}\n'.format(**config))

    for stake in config["stake_coords"]:
        outstring.append((" ".join(map(str, stake)) + "\n"))

    outstring = "".join(outstring)
    return outstring
